{% set version = "1.2.1" %}

package:
  name: libradolan
  version: {{ version }}

source:
  fn: libradolan-{{ version }}.tar.gz
  url: https://github.com/meteo-ubonn/radolan/archive/{{ version }}.tar.gz
  sha256: 650ffcdd5c62cfdfe54b2ebb3b868d674466e28e679e5db01305a790eabb1bad

build:
  number: 2
  skip: True   # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - netcdf-cxx4
    - shapelib

  run:
    - boost-cpp
    - netcdf-cxx4
    - shapelib

test:
  commands:
    - test -d $PREFIX/include/radolan  # [not win]
    - test -e $PREFIX/lib/libradolan.so  # [linux]
    - test -e $PREFIX/lib/libradolan.dylib  # [osx]
    - radolan2netcdf --version
    - radolan2netcdf --endianess
    - radolan2shapefile --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://meteo-ubonn.github.io/radolan/
  license: MIT
  license_file: LICENSE
  summary: 'C++ library for reading and working with the RADOLAN data format of the German Weather Service (DWD).'

extra:
  recipe-maintainers:
    - kmuehlbauer
    - JuergenSimon
