# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tXVbxELVHMcbhMqJS0g/E9IXO4xdhdu0q1TTahyu93i4A5PgyZjUvd9S0e8wMctZj0su8qsRPvyJHgyQTX8xz9GqrmpkZ7BtZT5vqTtvpee2OpekD0cXGiPg1CaOhO/z1U/qppaQDjZQD8l3D8gl4uMydaM9JX+jTnMOdscKJZPaHonVj/cuGRhpEqUZa+J+gJ3VWENkyj2zjXWPWGhlkbL4Lpk36lhVtEAgNiRqoyCNwU6dzIHqfkU39hC7A7/qMa4M5US76hr6w/1k1s/2YmN9xmsfPjdJlgNh1a+8K3NFKAES2TKNuwyWSHtQpHlEXHUMEudvUWyQreGNrgMOUPbW2fFOdNt54R2nrXfE5mAlb6kcKXc1fUUYQ3L/Ps9nROwXkt2OLCkmZQpKd3T9o27Dqck8iNKKLS76HxVuTM03C1+y+OrGWGzZdAoKpl190PqU4IcY9/V7s+3rae/YNtOGJvntICblYsKKTitVHh1WoRwgq0kHWPhEcSg+fIcJOhJ7zAmeBDyh6JARAe+9HezZq7KUzAjonQT5yGrCXI5lxH5dVWvWWDIic7DLzaKGhWZKvba3yw1V6u8qgxWDXU7jPOL2irEoXf/kk4zYpz6oRvgmwZfjqvfoZ4hqqnBBhV+k4iK/WsyKQea/PwShOjJdTALVsanFWjbfcMml6AQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
