travis:
  secure:
    BINSTAR_TOKEN: e0fTGEFTsit0A6VGaQuOlaDFMtceMozehPLa0u5+PYfE5BcmT4WSe905qsfvNZ+l9h3cwXRMd2hRDPZEheLgkY4jepQnyJIiFPNY5B70xnjLjrj1adbOcqPZ95BAVbNuBT0Oodbl7I5fJXR0l07+39Wsr014DE0XOPWF7LuBslGNgcrjYSGoVMnSXyzyYngfJ+aeYI89T3F0BF7/ryQ+GrJ1zE3h0f+XyMOY6/eDoQIkxZ+MlEbktFc6+dX4uka0+EcVWvsk7Oka8eBP6dU5+OdT/usOnpHtssYcG+sgPu3JFXtHNz6JOAJZ58SRkd+N7LpGWvLmXWW/lRZ/O7u6Q8stIhIE25KWRfKWmAzeub1qljeCnAJDuaUVlzhFBPW9Zvud5RXhLrHyK4Bj34i4p+kzx6Ks9ISYby5QwZpCr7zWvD6qInjb3c7SNcPuJRNYfbjoEQq7ZEkIRnyO59vuL8kcddtKzVQUq7twfIPG4ekpKc30+ZoXlVN+i3vj+KFK3LS1c5lnn6nWNeAlJf1Zw80YHe8Rx6ryowKGQZO48VZdw+mIDVwqJr982oUeORMEATbxwuP3WiPfYLBXb6wt/nBrH2IB225LAQxcfIeZBp1spPEPtqaKneKdiyQykV5XhKshqyDqdcqBhrcQy+EO/CpUxO3P8hekdQ7+Z6qypgI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
