travis:
  secure:
    BINSTAR_TOKEN: UbPiyTMislM7sIxNqLVFlz9T4rGn/YUThkcDB4tvrjl1djkUo+lHK+eMA8z09cnavsrVbGZczRXOlCpDOrwje7cjDXD5cSIyydSixubgAPd0KhXFk88IbLVec/WP8Z5b6d8w3OJQ4TpJa0+cXDQsJ7JP/hkg0IiRnZ0QSEWGZlkcagILHcewfn3Q4KvQ/XOrtvRmHt+SirYLXIl4BeinGDJUJrDsGTF6ynhh+HUobbHbXyG1/TJiLHuv6HPQOHqhDiNysNWjf1hAOciHP4i9pzm5sZNzjZbJe2z6jbquTeH39qWmsWpcaeSwDhV9FcJkHLwCtBCTanzu/+6xo1CEuPgt6pda+i4Fju6Q0cAcbCbEhHx8xAU3l/INDWn4R1l8unSmD8xQBYiZUE8/YzisGADt6Qqe4ZJbXYxUnllTexTc2lwiZfoam/Y9gwT24xMV3l49K4a8sRS5P7vH9NUJmQ7yCUXwS4XhQqb6x4FC8GZejTjzxoYqwBWlGR/HU6H2DmwspOQ7546mXSC8QQPdwhiAggAHOHTJ5l2CjNVgnfvmew2gOYEskHDnbtmBn2rdBBW82X4jlFOho9yV0FRICHKqjp1cz3i4dv7mGtmjjUlt0/u9Z898Tv7rVGuqXp/fIguSuLFd4CJhzejUWhXqpx5Rnr50vcdWg7tSySSVnHc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
