travis:
  secure:
    BINSTAR_TOKEN: W0btG+HLKWCWzxJpvdUpCQ3Syd755pFt+eZJsuQtiJTg2ILGeeiHpRsv7uyK5r3Uk/hMDsBTz61BRkvY67AETrapisQLlLmXHkfIk4h4kBKuBGOKkIm5w62hR8oaphl2qd3hH+9N+Z7aFPJooRNrG0ZMvmB1n0IGL+UXsO7XI5K8bbDhBN/jEy2Z2D9a6wn2mtvABqZaW7HuunwvzF9SodACZvO4y7qzWoIVrs5CRGJR3ugDExmxkuWSbtdrdyy7TdJFm4shzw24M32Bxv1vpSWW1YwoLoML0G3Sro+UFwVgH5ZaZ+wEMzQCU2MFbOERGKl2GCuMu1e6DEeJxOY30mr3+d8C473S2wlj9qhRRtcvCyz7T5tgf455n8ihCM+E1wvoRT8aMi1nZlNyAGcNzBDCJ6EGZQZ96fHfy79is68IAym+0qPJyP59errdJrB++VfL865rQE2YElAVxaj6c8zM/XAzDjuMp12n/toucxsnjWuIrxN9X71CAidE/FW8A2awRKqzLJNrLCZC/ysMzqaTNB7UH1snhBoVeEKmG6xhT+sCFhxWihAINPpZoQLCwFT1+LBH4my9uA80pH4lprnzNKAKFRG8DWNY+SBK28ML2qBowdbnJeb9UVwl4MsbX9XGeeprwTvSPk+z51ZyuDzrpzTzjuyfX0zoSTfIkw8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
